# Generated by Django 2.2.16 on 2022-06-28 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220628_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(error_messages={'validators': 'Укажите оценку от 1 до 10'}, validators=[django.core.validators.MinValueValidator(1, 'Рейтинг не может быть меньше единицы.'), django.core.validators.MaxValueValidator(10, 'Рейтинг не может быть бельше 10.')], verbose_name='Оценка'),
        ),
    ]
